name: Build and Deploy MkDocs to VPS

on:
  push:
    branches:
      - pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v6

      - name: Build MkDocs and Dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions
          mkdocs build --config-file docs/mkdocs.yml

      - name: Assemble site
        run: |
          rm -rf dist
          mkdir -p dist/d
          cp -r site/* dist/
          cp -r public/docs/* dist/d/

      # TODO: remove this once the issue is fixed
      - name: Test TCP reachability
        run: |
          nc -vz ${{ secrets.VPS_IP }} 22

      # Deploy to VPS using manual scp
      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: actions
          VPS_KEY: ${{ secrets.VPS_PRIV_KEY }}
        run: |
          printf '%s\n' "$VPS_KEY" > private_key
          chmod 600 private_key
      
          tar -C dist -cf - . | ssh \
            -i private_key \
            -o IdentitiesOnly=yes \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            $VPS_USER@$VPS_IP \
            'mkdir -p /home/actions/swiftlink && tar -C /home/actions/swiftlink -xf -'
      
          rm private_key
